config/routes.rb
Rails.application.routes.draw do
  resources :app_settings
  resources :take_actions
  resources :contacts
  resources :footers
  resources :headers
  resources :performances
  resources :services
  resources :abouts
  resources :stats, except: :destroy
  mount RailsAdmin::Engine => '/secret', as: 'rails_admin'
  devise_for :users
  resources :incoming_contacts
  resources :driver_applications
  resources :pages
  root to: 'pages#show' 

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/service.rb
class Service < ApplicationRecord
  rails_admin do
    configure :hide_service do
      label 'Hide page service: '
      help "When selected, the service partial will be hidden from the view. "
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:hide_service, :service_string_1, :service_string_2, :service_string_3, :service_string_4, :service_string_5, :service_string_6, :service_string_7, :service_string_8, :service_string_9, :service_string_10, :service_string_11, :service_string_12, :service_string_13, :service_string_14, :service_string_15, :service_string_16, :service_string_17, :service_string_18, :service_string_19, :service_string_20, :service_string_21, :service_string_22, :service_string_23, :service_string_24, :service_string_25, :service_string_26, :service_string_27, :service_string_28, :service_string_29, :service_string_30)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= simple_form_for(@service) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :string_1 %>
    <%= f.input :string_2 %>
    <%= f.input :string_3 %>
    <%= f.input :string_4 %>
    <%= f.input :string_5 %>
    <%= f.input :string_6 %>
    <%= f.input :string_7 %>
    <%= f.input :string_8 %>
    <%= f.input :string_9 %>
    <%= f.input :string_10 %>
    <%= f.input :string_11 %>
    <%= f.input :string_12 %>
    <%= f.input :string_13 %>
    <%= f.input :string_14 %>
    <%= f.input :string_15 %>
    <%= f.input :string_16 %>
    <%= f.input :string_17 %>
    <%= f.input :string_18 %>
    <%= f.input :string_19 %>
    <%= f.input :string_20 %>
    <%= f.input :string_21 %>
    <%= f.input :string_22 %>
    <%= f.input :string_23 %>
    <%= f.input :string_24 %>
    <%= f.input :string_25 %>
    <%= f.input :string_26 %>
    <%= f.input :string_27 %>
    <%= f.input :string_28 %>
    <%= f.input :string_29 %>
    <%= f.input :string_30 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>String 1</th>
      <th>String 2</th>
      <th>String 3</th>
      <th>String 4</th>
      <th>String 5</th>
      <th>String 6</th>
      <th>String 7</th>
      <th>String 8</th>
      <th>String 9</th>
      <th>String 10</th>
      <th>String 11</th>
      <th>String 12</th>
      <th>String 13</th>
      <th>String 14</th>
      <th>String 15</th>
      <th>String 16</th>
      <th>String 17</th>
      <th>String 18</th>
      <th>String 19</th>
      <th>String 20</th>
      <th>String 21</th>
      <th>String 22</th>
      <th>String 23</th>
      <th>String 24</th>
      <th>String 25</th>
      <th>String 26</th>
      <th>String 27</th>
      <th>String 28</th>
      <th>String 29</th>
      <th>String 30</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.string_1 %></td>
        <td><%= service.string_2 %></td>
        <td><%= service.string_3 %></td>
        <td><%= service.string_4 %></td>
        <td><%= service.string_5 %></td>
        <td><%= service.string_6 %></td>
        <td><%= service.string_7 %></td>
        <td><%= service.string_8 %></td>
        <td><%= service.string_9 %></td>
        <td><%= service.string_10 %></td>
        <td><%= service.string_11 %></td>
        <td><%= service.string_12 %></td>
        <td><%= service.string_13 %></td>
        <td><%= service.string_14 %></td>
        <td><%= service.string_15 %></td>
        <td><%= service.string_16 %></td>
        <td><%= service.string_17 %></td>
        <td><%= service.string_18 %></td>
        <td><%= service.string_19 %></td>
        <td><%= service.string_20 %></td>
        <td><%= service.string_21 %></td>
        <td><%= service.string_22 %></td>
        <td><%= service.string_23 %></td>
        <td><%= service.string_24 %></td>
        <td><%= service.string_25 %></td>
        <td><%= service.string_26 %></td>
        <td><%= service.string_27 %></td>
        <td><%= service.string_28 %></td>
        <td><%= service.string_29 %></td>
        <td><%= service.string_30 %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String 1:</strong>
  <%= @service.string_1 %>
</p>

<p>
  <strong>String 2:</strong>
  <%= @service.string_2 %>
</p>

<p>
  <strong>String 3:</strong>
  <%= @service.string_3 %>
</p>

<p>
  <strong>String 4:</strong>
  <%= @service.string_4 %>
</p>

<p>
  <strong>String 5:</strong>
  <%= @service.string_5 %>
</p>

<p>
  <strong>String 6:</strong>
  <%= @service.string_6 %>
</p>

<p>
  <strong>String 7:</strong>
  <%= @service.string_7 %>
</p>

<p>
  <strong>String 8:</strong>
  <%= @service.string_8 %>
</p>

<p>
  <strong>String 9:</strong>
  <%= @service.string_9 %>
</p>

<p>
  <strong>String 10:</strong>
  <%= @service.string_10 %>
</p>

<p>
  <strong>String 11:</strong>
  <%= @service.string_11 %>
</p>

<p>
  <strong>String 12:</strong>
  <%= @service.string_12 %>
</p>

<p>
  <strong>String 13:</strong>
  <%= @service.string_13 %>
</p>

<p>
  <strong>String 14:</strong>
  <%= @service.string_14 %>
</p>

<p>
  <strong>String 15:</strong>
  <%= @service.string_15 %>
</p>

<p>
  <strong>String 16:</strong>
  <%= @service.string_16 %>
</p>

<p>
  <strong>String 17:</strong>
  <%= @service.string_17 %>
</p>

<p>
  <strong>String 18:</strong>
  <%= @service.string_18 %>
</p>

<p>
  <strong>String 19:</strong>
  <%= @service.string_19 %>
</p>

<p>
  <strong>String 20:</strong>
  <%= @service.string_20 %>
</p>

<p>
  <strong>String 21:</strong>
  <%= @service.string_21 %>
</p>

<p>
  <strong>String 22:</strong>
  <%= @service.string_22 %>
</p>

<p>
  <strong>String 23:</strong>
  <%= @service.string_23 %>
</p>

<p>
  <strong>String 24:</strong>
  <%= @service.string_24 %>
</p>

<p>
  <strong>String 25:</strong>
  <%= @service.string_25 %>
</p>

<p>
  <strong>String 26:</strong>
  <%= @service.string_26 %>
</p>

<p>
  <strong>String 27:</strong>
  <%= @service.string_27 %>
</p>

<p>
  <strong>String 28:</strong>
  <%= @service.string_28 %>
</p>

<p>
  <strong>String 29:</strong>
  <%= @service.string_29 %>
</p>

<p>
  <strong>String 30:</strong>
  <%= @service.string_30 %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>