config/routes.rb
Rails.application.routes.draw do
  resources :app_settings
  resources :take_actions
  resources :contacts
  resources :footers
  resources :headers
  resources :performances
  resources :services
  resources :abouts
  resources :stats, except: :destroy
  mount RailsAdmin::Engine => '/secret', as: 'rails_admin'
  devise_for :users
  resources :incoming_contacts
  resources :driver_applications
  resources :pages
  root to: 'pages#show' 

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/footer.rb
class Footer < ApplicationRecord

  enum footer_font_awesome: FontAwesomeSolid


  rails_admin do
    configure :hide_footer do
      label 'Hide page footer: '
      help "When selected, the footer partial will be hidden from the view. "
    end
    configure :footer_string_1 do
      label 'Text Input 1: '
      help " "
    end
    configure :footer_string_2 do
      label 'Text Input 2: '
      help " "
    end
    configure :footer_string_3 do
      label 'Text Input 3: '
      help " "
    end
    configure :footer_string_4 do
      label 'Text Input 4: '
      help " "
    end
    configure :footer_string_5 do
      label 'Text Input 5: '
      help " "
    end
    configure :footer_font_awesome do
      label 'Font Awesome Icon: '
      help "To preview icons visit fontawesome.com/icons"

    end
  end
end

app/controllers/footers_controller.rb
class FootersController < ApplicationController
  before_action :set_footer, only: [:show, :edit, :update, :destroy]

  # GET /footers
  # GET /footers.json
  def index
    @footers = Footer.all
  end

  # GET /footers/1
  # GET /footers/1.json
  def show
  end

  # GET /footers/new
  def new
    @footer = Footer.new
  end

  # GET /footers/1/edit
  def edit
  end

  # POST /footers
  # POST /footers.json
  def create
    @footer = Footer.new(footer_params)

    respond_to do |format|
      if @footer.save
        format.html { redirect_to @footer, notice: 'Footer was successfully created.' }
        format.json { render :show, status: :created, location: @footer }
      else
        format.html { render :new }
        format.json { render json: @footer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /footers/1
  # PATCH/PUT /footers/1.json
  def update
    respond_to do |format|
      if @footer.update(footer_params)
        format.html { redirect_to @footer, notice: 'Footer was successfully updated.' }
        format.json { render :show, status: :ok, location: @footer }
      else
        format.html { render :edit }
        format.json { render json: @footer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /footers/1
  # DELETE /footers/1.json
  def destroy
    @footer.destroy
    respond_to do |format|
      format.html { redirect_to footers_url, notice: 'Footer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_footer
      @footer = Footer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def footer_params
      params.require(:footer).permit(:hide_footer, :footer_string_1, :footer_string_2, :footer_string_3, :footer_string_4, :footer_string_5, :footer_font_awesome)
    end
end

app/helpers/footers_helper.rb
module FootersHelper
end

app/views/footers/_form.html.erb
<%= simple_form_for(@footer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :string_1 %>
    <%= f.input :string_2 %>
    <%= f.input :string_3 %>
    <%= f.input :string_4 %>
    <%= f.input :string_5 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/footers/edit.html.erb
<h1>Editing Footer</h1>

<%= render 'form', footer: @footer %>

<%= link_to 'Show', @footer %> |
<%= link_to 'Back', footers_path %>

app/views/footers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Footers</h1>

<table>
  <thead>
    <tr>
      <th>String 1</th>
      <th>String 2</th>
      <th>String 3</th>
      <th>String 4</th>
      <th>String 5</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @footers.each do |footer| %>
      <tr>
        <td><%= footer.string_1 %></td>
        <td><%= footer.string_2 %></td>
        <td><%= footer.string_3 %></td>
        <td><%= footer.string_4 %></td>
        <td><%= footer.string_5 %></td>
        <td><%= link_to 'Show', footer %></td>
        <td><%= link_to 'Edit', edit_footer_path(footer) %></td>
        <td><%= link_to 'Destroy', footer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Footer', new_footer_path %>

app/views/footers/new.html.erb
<h1>New Footer</h1>

<%= render 'form', footer: @footer %>

<%= link_to 'Back', footers_path %>

app/views/footers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String 1:</strong>
  <%= @footer.string_1 %>
</p>

<p>
  <strong>String 2:</strong>
  <%= @footer.string_2 %>
</p>

<p>
  <strong>String 3:</strong>
  <%= @footer.string_3 %>
</p>

<p>
  <strong>String 4:</strong>
  <%= @footer.string_4 %>
</p>

<p>
  <strong>String 5:</strong>
  <%= @footer.string_5 %>
</p>

<%= link_to 'Edit', edit_footer_path(@footer) %> |
<%= link_to 'Back', footers_path %>