config/routes.rb
Rails.application.routes.draw do
  resources :app_settings
  resources :take_actions
  resources :contacts
  resources :footers
  resources :headers
  resources :performances
  resources :services
  resources :abouts
  resources :stats, except: :destroy
  mount RailsAdmin::Engine => '/secret', as: 'rails_admin'
  devise_for :users
  resources :incoming_contacts
  resources :driver_applications
  resources :pages
  root to: 'pages#show' 

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/app_setting.rb
class AppSetting < ApplicationRecord
  has_one_attached :logo_image
  def logo_image_variant
    return self.logo_image.variant(resize: '100x50!') if self.logo_image.attached? 
  end

  def logo_image_resized
    return self.logo_image.variant(resize: '200x100!') if self.logo_image.attached? 
  end

  rails_admin do
    configure :string_1 do
      label 'Logo text 1: '
      help " "
    end
    configure :string_2 do
      label 'Logo text 2: '
      help " "
    end
    configure :string_3 do
      label 'Logo text 3: '
      help " "
    end
    configure :string_3 do
      label 'Logo text 3: '
      help " "
    end
    configure :string_3 do
      label 'Logo text 3: '
      help " "
    end
    configure :mailer_send_to_email1 do
      label 'Contact form email: '
      help "Enter the email address where you want to receive the contact form emails "
    end
    configure :mailer_send_to_email2 do
      label 'Driver application form email: '
      help "Enter the email address where you want to receive driver application emails "
    end
    configure :string_4 do
      label 'Application title: '
      help " Browser tab text"
    end
    configure :string_5 do
      label 'This input not assigned: '
      help " "
    end
    configure :boolean_1 do
      label 'This input not assigned: '
      help " Extra bool no function assigned  "
    end
    configure :boolean_2 do
      label 'This input not assigned: '
      help " Extra bool no function assigned  "
    end


  end
end

app/controllers/app_settings_controller.rb
class AppSettingsController < ApplicationController
  before_action :set_app_setting, only: [:show, :edit, :update, :destroy]

  # GET /app_settings
  # GET /app_settings.json
  def index
    @app_settings = AppSetting.all
  end

  # GET /app_settings/1
  # GET /app_settings/1.json
  def show
  end

  # GET /app_settings/new
  def new
    @app_setting = AppSetting.new
  end

  # GET /app_settings/1/edit
  def edit
  end

  # POST /app_settings
  # POST /app_settings.json
  def create
    @app_setting = AppSetting.new(app_setting_params)

    respond_to do |format|
      if @app_setting.save
        format.html { redirect_to @app_setting, notice: 'App setting was successfully created.' }
        format.json { render :show, status: :created, location: @app_setting }
      else
        format.html { render :new }
        format.json { render json: @app_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_settings/1
  # PATCH/PUT /app_settings/1.json
  def update
    respond_to do |format|
      if @app_setting.update(app_setting_params)
        format.html { redirect_to @app_setting, notice: 'App setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_setting }
      else
        format.html { render :edit }
        format.json { render json: @app_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_settings/1
  # DELETE /app_settings/1.json
  def destroy
    @app_setting.destroy
    respond_to do |format|
      format.html { redirect_to app_settings_url, notice: 'App setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_setting
      @app_setting = AppSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_setting_params
      params.require(:app_setting).permit(:mailer_send_to_email1, :mailer_send_to_email2, :string_1, :string_2, :string_3, :string_4, :string_5, :boolean_1, :boolean_2, :hide_logo_text, :hide_logo_image)
    end
end

app/helpers/app_settings_helper.rb
module AppSettingsHelper
end

app/views/app_settings/_form.html.erb
<%= simple_form_for(@app_setting) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :mailer_send_to_email1 %>
    <%= f.input :mailer_send_to_email2 %>
    <%= f.input :string_1 %>
    <%= f.input :string_2 %>
    <%= f.input :string_3 %>
    <%= f.input :string_4 %>
    <%= f.input :string_5 %>
    <%= f.input :boolian_1 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/app_settings/edit.html.erb
<h1>Editing App Setting</h1>

<%= render 'form', app_setting: @app_setting %>

<%= link_to 'Show', @app_setting %> |
<%= link_to 'Back', app_settings_path %>

app/views/app_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>App Settings</h1>

<table>
  <thead>
    <tr>
      <th>Mailer send to email1</th>
      <th>Mailer send to email2</th>
      <th>String 1</th>
      <th>String 2</th>
      <th>String 3</th>
      <th>String 4</th>
      <th>String 5</th>
      <th>Boolian 1</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_settings.each do |app_setting| %>
      <tr>
        <td><%= app_setting.mailer_send_to_email1 %></td>
        <td><%= app_setting.mailer_send_to_email2 %></td>
        <td><%= app_setting.string_1 %></td>
        <td><%= app_setting.string_2 %></td>
        <td><%= app_setting.string_3 %></td>
        <td><%= app_setting.string_4 %></td>
        <td><%= app_setting.string_5 %></td>
        <td><%= app_setting.boolian_1 %></td>
        <td><%= link_to 'Show', app_setting %></td>
        <td><%= link_to 'Edit', edit_app_setting_path(app_setting) %></td>
        <td><%= link_to 'Destroy', app_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App Setting', new_app_setting_path %>

app/views/app_settings/new.html.erb
<h1>New App Setting</h1>

<%= render 'form', app_setting: @app_setting %>

<%= link_to 'Back', app_settings_path %>

app/views/app_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mailer send to email1:</strong>
  <%= @app_setting.mailer_send_to_email1 %>
</p>

<p>
  <strong>Mailer send to email2:</strong>
  <%= @app_setting.mailer_send_to_email2 %>
</p>

<p>
  <strong>String 1:</strong>
  <%= @app_setting.string_1 %>
</p>

<p>
  <strong>String 2:</strong>
  <%= @app_setting.string_2 %>
</p>

<p>
  <strong>String 3:</strong>
  <%= @app_setting.string_3 %>
</p>

<p>
  <strong>String 4:</strong>
  <%= @app_setting.string_4 %>
</p>

<p>
  <strong>String 5:</strong>
  <%= @app_setting.string_5 %>
</p>

<p>
  <strong>Boolian 1:</strong>
  <%= @app_setting.boolian_1 %>
</p>

<%= link_to 'Edit', edit_app_setting_path(@app_setting) %> |
<%= link_to 'Back', app_settings_path %>