config/routes.rb
Rails.application.routes.draw do
  resources :app_settings
  resources :take_actions
  resources :contacts
  resources :footers
  resources :headers
  resources :performances
  resources :services
  resources :abouts
  resources :stats, except: :destroy
  mount RailsAdmin::Engine => '/secret', as: 'rails_admin'
  devise_for :users
  resources :incoming_contacts
  resources :driver_applications
  resources :pages
  root to: 'pages#show' 

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/header.rb
class Header < ApplicationRecord


  has_one_attached :header_image
  def header_nail
    return self.header_image.variant(resize: '100x100') if self.header_image.attached? 
  end

  def header_image_variant
    return self.header_image.variant(resize: '3000x2000!') if self.header_image.attached? 
  end

  rails_admin do

    configure :hide_header do
      label 'Hide page header: '
      help "When selected, the header partial will be hidden from the view. "
    end

    configure :header_string_1 do
      label 'Text Input 1: '
      help " "
    end
    configure :header_string_2 do
      label 'Text Input 2: '
      help " "
    end
    configure :header_string_3 do
      label 'Text Input 3: '
      help " "
    end
    configure :header_string_4 do
      label 'Button Text: '
      help " "
    end
    configure :header_image do
      label 'Image File: '
      help "For best results image size should be 3000 x 2000 px"
    end
  end
end

app/controllers/headers_controller.rb
class HeadersController < ApplicationController
  before_action :set_header, only: [:show, :edit, :update, :destroy]

  # GET /headers
  # GET /headers.json
  def index
    @headers = Header.all
  end

  # GET /headers/1
  # GET /headers/1.json
  def show
  end

  # GET /headers/new
  def new
    @header = Header.new
  end

  # GET /headers/1/edit
  def edit
  end

  # POST /headers
  # POST /headers.json
  def create
    @header = Header.new(header_params)

    respond_to do |format|
      if @header.save
        format.html { redirect_to @header, notice: 'Header was successfully created.' }
        format.json { render :show, status: :created, location: @header }
      else
        format.html { render :new }
        format.json { render json: @header.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /headers/1
  # PATCH/PUT /headers/1.json
  def update
    respond_to do |format|
      if @header.update(header_params)
        format.html { redirect_to @header, notice: 'Header was successfully updated.' }
        format.json { render :show, status: :ok, location: @header }
      else
        format.html { render :edit }
        format.json { render json: @header.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /headers/1
  # DELETE /headers/1.json
  def destroy
    @header.destroy
    respond_to do |format|
      format.html { redirect_to headers_url, notice: 'Header was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_header
      @header = Header.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def header_params
      params.require(:header).permit(:hide_header, :header_string_1, :header_string_2, :header_string_3, :header_string_4)
    end
end

app/helpers/headers_helper.rb
module HeadersHelper
end

app/views/headers/_form.html.erb
<%= simple_form_for(@header) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :string_1 %>
    <%= f.input :string_2 %>
    <%= f.input :string_3 %>
    <%= f.input :string_4 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/headers/edit.html.erb
<h1>Editing Header</h1>

<%= render 'form', header: @header %>

<%= link_to 'Show', @header %> |
<%= link_to 'Back', headers_path %>

app/views/headers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Headers</h1>

<table>
  <thead>
    <tr>
      <th>String 1</th>
      <th>String 2</th>
      <th>String 3</th>
      <th>String 4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @headers.each do |header| %>
      <tr>
        <td><%= header.string_1 %></td>
        <td><%= header.string_2 %></td>
        <td><%= header.string_3 %></td>
        <td><%= header.string_4 %></td>
        <td><%= link_to 'Show', header %></td>
        <td><%= link_to 'Edit', edit_header_path(header) %></td>
        <td><%= link_to 'Destroy', header, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Header', new_header_path %>

app/views/headers/new.html.erb
<h1>New Header</h1>

<%= render 'form', header: @header %>

<%= link_to 'Back', headers_path %>

app/views/headers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String 1:</strong>
  <%= @header.string_1 %>
</p>

<p>
  <strong>String 2:</strong>
  <%= @header.string_2 %>
</p>

<p>
  <strong>String 3:</strong>
  <%= @header.string_3 %>
</p>

<p>
  <strong>String 4:</strong>
  <%= @header.string_4 %>
</p>

<%= link_to 'Edit', edit_header_path(@header) %> |
<%= link_to 'Back', headers_path %>